redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ''

mysql:
  path: 127.0.0.1
  config: charset=utf8&parseTime=True&loc=Local
  db-name: douyin
  username: root
  password: 123456
  max-idle-conns: 10
  max-open-conns: 100

qiniu:
  bucket: xlong99
  accessKey: JafZdnNs3QlssMUSi0LQqA5befbowM7HyibjCexQ
  secretKey: zY-0Qbyie8s1I_kWlCzy07-NIAtR0v66COV1gKq6


# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: 'mysql'