redis:
  db: 0
  addr: 47.96.157.235:6379
  password: '000415'

mysql:
  path: 121.40.134.218
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: douyin
  username: douyin
  password: zijiefan
  max-idle-conns: 10
  max-open-conns: 100

qiniu:
  bucket: xlong99
  accessKey: JafZdnNs3QlssMUSi0LQqA5befbowM7HyibjCexQ
  secretKey: zY-0Qbyie8s1I_kWlCzy07-NIAtR0v66COV1gKq6


# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: 'mysql'