// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/DouYin/cmd/api/rpc"
	"github.com/DouYin/hertz_gen/model/hertz/user"
	user1 "github.com/DouYin/kitex_gen/user"
	"github.com/DouYin/pkg/errno"
	"github.com/cloudwego/hertz/pkg/app"
	"net/http"
)

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var loginReq user.LoginReq
	err = c.BindAndValidate(&loginReq)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	resp := new(user.LoginResp)
	c.JSON(200, resp)
}

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var registerVar user.RegisterReq
	err = c.BindAndValidate(&registerVar)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	usr, err := rpc.CreateUser(context.Background(), &user1.CreateUserRequest{
		Username: registerVar.Username,
		Password: registerVar.Password,
	})
	if err != nil {
		e := errno.ConvertErr(err)
		c.JSON(http.StatusOK, BaseResponse{
			Code: e.ErrCode,
			Msg:  e.ErrMsg,
		})
		return
	}
	resp := new(user.RegisterResp)
	e := errno.Success
	c.JSON(200, resp)
}

// User .
// @router /user [GET]
func User(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(user.UserResp)

	c.JSON(200, resp)
}
