// Code generated by hertz generator.

package user

import (
	"context"

	user "github.com/DouYin/biz/model/hertz/user"
	"github.com/cloudwego/hertz/pkg/app"
)

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(user.LoginResp)

	c.JSON(200, resp)
}

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(user.RegisterResp)

	c.JSON(200, resp)
}

// User .
// @router /user [GET]
func User(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(user.UserResp)

	c.JSON(200, resp)
}
